import { Search } from "lucide-react";
import React, { useState, useEffect, useRef } from 'react';
import { 
  ArrowLeft, 
  Save, 
  X, 
  Upload, 
  CheckCircle2, 
  AlertCircle,
  Eye,
  EyeOff,
  Edit2,
  Image as ImageIcon,
  Camera,
  RefreshCw,
  Check,
  Edit3,
  ToggleLeft,
  ToggleRight,
  Trash2
} from 'lucide-react';
import { 
  UserGroup, 
  UserType, 
  Department,
  DepartmentEntry 
} from '../../types';
import { TransactionOverlay, TransactionStatus } from '../TransactionOverlay';
import { StatusConfirmationModal } from '../StatusConfirmationModal';

interface UserManagementProps {
  onBack: () => void;
}

const Mandatory = () => <span className="text-rose-500 ml-0.5">*</span>;

// Mock Doctor Registry
const DOCTORS = [
  "DR. JAYVEE PALISOC",
  "DR. MARK QUINTOS",
  "DR. ANA DELA CRUZ",
  "DR. MARIA CLARA SANTOS",
  "DR. JUAN DELA CRUZ",
  "DR. JULIUS K. QUIAMBAO"
];

export const UserManagement: React.FC<UserManagementProps> = ({ onBack }) => {
  const [showForm, setShowForm] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [showCamera, setShowCamera] = useState(false);
  const [usernameAutoGenerated, setUsernameAutoGenerated] = useState(false);
  const [departments, setDepartments] = useState<DepartmentEntry[]>([]);
  const [users, setUsers] = useState<any[]>([]);
  const [editId, setEditId] = useState<string | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const colorMap: Record<string, string> = {
    emerald: "bg-emerald-100 text-emerald-700",
    blue: "bg-blue-100 text-blue-700",
    orange: "bg-orange-100 text-orange-700"
  };

  
  // Transaction State
  const [txStatus, setTxStatus] = useState<TransactionStatus>('idle');
  const [txMsg, setTxMsg] = useState('');

  // Status Modal State
  const [statusModal, setStatusModal] = useState<{
  isOpen: boolean;
  user: any | null;
  action: "activate" | "deactivate" | null;
}>({
  isOpen: false,
  user: null,
  action: null
});

  // Header Editing State
  const [isEditingSubtitle, setIsEditingSubtitle] = useState(false);
  const [subtitle, setSubtitle] = useState(() => localStorage.getItem('user_mgmt_subtitle') || 'SETUP CONSOLE • STAFF DIRECTORY');

  const fileInputRef = useRef<HTMLInputElement>(null);
  const photoInputRef = useRef<HTMLInputElement>(null);
  const videoRef = useRef<HTMLVideoElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);

  const initialFormState = {
    lastName: '',
    firstName: '',
    middleName: '',
    extension: '',
    username: '',
    customName: '',
    email: '',
    departments: [] as string[],
    defaultDepartment: '',
    password: '',
    confirmPassword: '',
    userGroup: UserGroup.User,
    userType: UserType.ADMIN,
    isActive: true,
    eSignature: null as string | null,
    profileImage: null as string | null,
    doctorName: ''
  };

  const [formData, setFormData] = useState(initialFormState);
  const [errors, setErrors] = useState<Record<string, string>>({});

useEffect(() => {
  fetchDepartments();
  fetchUsers();
}, []);

  const handleSaveSubtitle = () => {
    localStorage.setItem('user_mgmt_subtitle', subtitle.toUpperCase());
    setIsEditingSubtitle(false);
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
    const { name, value } = e.target;
    const transformedValue = value;
    
    setFormData(prev => {
      const newState = { ...prev, [name]: transformedValue };
      
      if (!editId && !usernameAutoGenerated && ['lastName', 'firstName', 'middleName'].includes(name)) {
        const firstInitial = newState.firstName.charAt(0);
        const middleInitial = newState.middleName.charAt(0);
        const lastNamePart = newState.lastName.replace(/\s+/g, '');
        
        if (firstInitial || lastNamePart) {
          newState.username = (firstInitial + middleInitial + lastNamePart).toUpperCase();
        }
      }

      // Reset doctorName if userType is changed from Doctor
      if (name === 'userType' && value !== UserType.DOCTOR) {
        newState.doctorName = '';
      }
      
      return newState;
    });

    if (errors[name]) {
      setErrors(prev => {
        const newErrs = { ...prev };
        delete newErrs[name];
        return newErrs;
      });
    }
  };

const toggleDepartment = (deptCode: string) => {
  setFormData(prev => {
    const exists = prev.departments.includes(deptCode);

    let updatedDepts = exists
      ? prev.departments.filter(d => d !== deptCode)
      : [...prev.departments, deptCode];

    let newDefault = prev.defaultDepartment;

    if (exists && prev.defaultDepartment === deptCode) {
      newDefault = updatedDepts.length > 0 ? updatedDepts[0] : '';
    } else if (!exists && updatedDepts.length === 1) {
      newDefault = deptCode;
    }

    return {
      ...prev,
      departments: updatedDepts,
      defaultDepartment: newDefault
    };
  });
};


  const handleUsernameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setFormData(prev => ({ ...prev, username: e.target.value.toUpperCase() }));
    setUsernameAutoGenerated(true); 
  };

const handleFileChange = (
  e: React.ChangeEvent<HTMLInputElement>,
  type: 'signature' | 'photo'
) => {
  const file = e.target.files?.[0];
  if (!file) return;

  // 🔥 Only for preview
  const reader = new FileReader();
  reader.onloadend = () => {
    if (type === 'signature') {
      setFormData(prev => ({
        ...prev,
        eSignature: reader.result as string
      }));
    } else {
      setFormData(prev => ({
        ...prev,
        profileImage: reader.result as string
      }));
    }
  };
  reader.readAsDataURL(file);
};

  const startCamera = async () => {
    setShowCamera(true);
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ video: true });
      if (videoRef.current) videoRef.current.srcObject = stream;
    } catch (err) {
      setShowCamera(false);
      alert("Could not access camera.");
    }
  };

  const stopCamera = () => {
    if (videoRef.current && videoRef.current.srcObject) {
      const stream = videoRef.current.srcObject as MediaStream;
      stream.getTracks().forEach(track => track.stop());
    }
    setShowCamera(false);
  };

  const capturePhoto = () => {
    if (videoRef.current && canvasRef.current) {
      const context = canvasRef.current.getContext('2d');
      if (context) {
        canvasRef.current.width = videoRef.current.videoWidth;
        canvasRef.current.height = videoRef.current.videoHeight;
        context.drawImage(videoRef.current, 0, 0, canvasRef.current.width, canvasRef.current.height);
        setFormData(prev => ({ ...prev, profileImage: canvasRef.current!.toDataURL('image/png') }));
        stopCamera();
      }
    }
  };

  const validate = () => {
    const newErrors: Record<string, string> = {};
    if (!formData.lastName) newErrors.lastName = 'Last Name is required';
    if (!formData.firstName) newErrors.firstName = 'First Name is required';
    if (!formData.username) newErrors.username = 'Username is required';
    if (!formData.email || !/\S+@\S+\.\S+/.test(formData.email)) newErrors.email = 'Valid email is required';
    if (formData.departments.length === 0) newErrors.departments = 'Select at least one department';
    if (!formData.defaultDepartment) newErrors.defaultDepartment = 'Default Station required';
    
    if (formData.userType === UserType.DOCTOR && !formData.doctorName) {
      newErrors.doctorName = 'Associate Doctor is required for Doctor user type';
    }

// Only validate password if creating OR if user typed a new password
if (!editId) {
  // Creating new user — password required
  if (!formData.password) {
    newErrors.password = 'Password is required.';
  }
}

if (formData.password && formData.password.trim() !== '') {
  const passRegex =
    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;

  if (!passRegex.test(formData.password)) {
    newErrors.password =
      'Required: 8+ characters, uppercase, lowercase, number, and special character.';
  }

  if (formData.password !== formData.confirmPassword) {
    newErrors.confirmPassword = 'Passwords do not match.';
  }
}

    
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };
const fetchDepartments = async () => {
  try {
    const res = await fetch(
  `${import.meta.env.VITE_API_URL}/api/departments`
);
    if (!res.ok) throw new Error("Failed to fetch departments");

    const data = await res.json();
    if (!Array.isArray(data)) {
      setDepartments([]);
      return;
    }

    const mapped: DepartmentEntry[] = data.map((d: any) => ({
      id: d.auto_id?.toString() || "",
      name: d.dept_name || "",
      code: d.dept_code || "",
      status: d.dept_status || ""
    }));

    setDepartments(mapped);
  } catch (err) {
    console.error("Department fetch error:", err);
    setDepartments([]);
  }
};

const fetchUsers = async () => {
  try {
    const res = await fetch(
  `${import.meta.env.VITE_API_URL}/api/users`
)
    if (!res.ok) throw new Error("Failed to fetch users");

    const data = await res.json();
    if (!Array.isArray(data)) {
      setUsers([]);
     return;
    }

    const mapped = data.map((u: any) => ({
      id: u.auto_id?.toString() || "",
      username: u.usr_username || "",
      fullName: u.full_name || "",
      userGroup: u.fk_usr_group_code || "",
      userType: u.fk_usr_type_code || "",
      isActive: Boolean(u.usr_status_active),
statusLabel: u.usr_status_active ? "ACTIVE" : "DEACTIVATED",
      defaultDepartment: u.default_department_name || "",
      departments: u.departments || [],
      doctorName: u.doctor_name || "",
	  groupColor: u.group_color || null,
    }));

    setUsers(mapped);
  } catch (err) {
    console.error("User fetch error:", err);
    setUsers([]);
  }
};
const filteredUsers = users.filter((u: any) => {
  const term = searchTerm.toLowerCase();

  return (
    u.username?.toLowerCase().includes(term) ||
    u.fullName?.toLowerCase().includes(term) ||
    u.userGroup?.toLowerCase().includes(term) ||
    u.statusLabel?.toLowerCase().includes(term)
  );
});


 const handleSave = async () => {
  if (!validate()) return;

  setTxStatus('loading');
  setTxMsg(editId ? 'Updating user profile...' : 'Saving user profile...');

  const startTime = Date.now();

  try {
    const formDataToSend = new FormData();

    formDataToSend.append("usr_last_name", formData.lastName);
    formDataToSend.append("usr_first_name", formData.firstName);
    formDataToSend.append("usr_middle_name", formData.middleName);
    formDataToSend.append("usr_extension", formData.extension);
    formDataToSend.append("usr_username", formData.username);
    formDataToSend.append("usr_email", formData.email);
    formDataToSend.append("usr_password", formData.password);
    formDataToSend.append("fk_usr_group_code", formData.userGroup);
    formDataToSend.append("fk_usr_type_code", formData.userType);
    formDataToSend.append("usr_status_active", String(formData.isActive));
    formDataToSend.append("defaultDepartment", formData.defaultDepartment);
    formDataToSend.append("doctorName", formData.doctorName);

    // Departments array
    formData.departments.forEach((dept) => {
      formDataToSend.append("departments[]", dept);
    });

    // 🔥 IMPORTANT — send real FILE objects
    if (photoInputRef.current?.files?.[0]) {
      formDataToSend.append("profileImage", photoInputRef.current.files[0]);
    }

    if (fileInputRef.current?.files?.[0]) {
      formDataToSend.append("signature", fileInputRef.current.files[0]);
    }

    const url = editId
      ? `${import.meta.env.VITE_API_URL}/api/users/${editId}`
      : `${import.meta.env.VITE_API_URL}/api/users`;

    const res = await fetch(url, {
      method: editId ? "PUT" : "POST",
      body: formDataToSend   // ❌ DO NOT set Content-Type
    });

    if (!res.ok) {
      const errData = await res.json();
      throw new Error(errData.message || "Save failed");
    }

    await fetchUsers();

    const elapsed = Date.now() - startTime;
    const remaining = Math.max(700 - elapsed, 0);

    setTimeout(() => {
      setTxStatus('success');
      setTxMsg(editId ? 'User updated successfully.' : 'User saved successfully.');

      setTimeout(() => {
        setShowForm(false);
        setEditId(null);
        setFormData(initialFormState);
        setTxStatus('idle');
      }, 800);

    }, remaining);

  } catch (err: any) {
    console.error(err);
    setTxStatus("error");
    setTxMsg(err.message || "Failed to save user.");

    setTimeout(() => {
      setTxStatus("idle");
    }, 7000);
  }
};




 const handleEdit = async (user: any) => {
  try {
    const res = await fetch(`${import.meta.env.VITE_API_URL}/api/users/${user.id}`);
    if (!res.ok) throw new Error("Failed to fetch user details");

    const data = await res.json();

    setEditId(user.id);

    setFormData({
  lastName: data.usr_last_name || '',
  firstName: data.usr_first_name || '',
  middleName: data.usr_middle_name || '',
  extension: data.usr_extension || '',
  username: data.usr_username || '',
  customName: data.usr_custom_name || '',
  email: data.usr_email || '',
  userGroup: data.fk_usr_group_code,
  userType: data.fk_usr_type_code,
  isActive: Boolean(data.usr_status_active),
  defaultDepartment: data.defaultDepartment || '',
  doctorName: data.usr_associate_doctor_name || '',
  profileImage: data.usr_photo_path || null,
  eSignature: data.usr_signature_path || null,
  departments: data.departments || [],
  password: '',
  confirmPassword: ''
});


    setShowForm(true);

  } catch (err) {
    console.error(err);
    alert("Failed to load user details.");
  }
};

const handleToggleStatus = async () => {
  if (!statusModal.user) return;

  const user = statusModal.user;

  const newStatus = !user.isActive; // ✅ only one declaration

  setTxStatus("loading");
  setTxMsg("Updating status...");

  try {
    const res = await fetch(
      `${import.meta.env.VITE_API_URL}/api/users/${user.id}/status`,
      {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          usr_status_active: newStatus, // ✅ boolean
        }),
      }
    );

    if (!res.ok) throw new Error("Status update failed");

    await fetchUsers();

    setTxStatus("success");
    setTxMsg("Status updated.");
    setTimeout(() => setTxStatus("idle"), 800);

  } catch (err) {
    console.error(err);
    setTxStatus("error");
    setTxMsg("Failed to update status.");
  }

  setStatusModal({ isOpen: false, user: null, action: null });
};


  return (
<div className="space-y-6 animate-in fade-in duration-500">
  <div className="flex items-center justify-between">
    
    {/* LEFT SIDE — BACK + TITLE + SUBTITLE */}
    <div className="flex items-center gap-4">
      <button
        onClick={onBack}
        className="p-2.5 bg-white border border-slate-200 text-slate-400 hover:text-slate-800 rounded-xl transition-all shadow-sm"
      >
        <ArrowLeft size={20} />
      </button>

      <div>
        <h2 className="text-2xl font-black text-slate-800 uppercase tracking-tight leading-none mb-1">
          User Management
        </h2>

        <div className="flex items-center gap-2 group">
          {isEditingSubtitle ? (
            <div className="flex items-center gap-2">
              <input
                type="text"
                value={subtitle}
                onChange={(e) =>
                  setSubtitle(e.target.value.toUpperCase())
                }
                onBlur={handleSaveSubtitle}
                autoFocus
                className="text-[10px] font-black text-emerald-600 border-b border-emerald-300 outline-none bg-emerald-50 px-1 uppercase tracking-widest"
              />
            </div>
          ) : (
            <>
              <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">
                {subtitle}
              </p>
              <button
                onClick={() => setIsEditingSubtitle(true)}
                className="opacity-0 group-hover:opacity-100 p-1 text-slate-300 hover:text-emerald-500 transition-all"
              >
                <Edit3 size={10} />
              </button>
            </>
          )}
        </div>
      </div>
    </div>

    {/* RIGHT SIDE — SEARCH + ADD BUTTON */}
    {!showForm && (
      <div className="flex items-center gap-4">
        
        {/* SEARCH INPUT */}
        <div className="relative w-80">
          <Search
            size={16}
            className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400"
          />
          <input
            type="text"
            placeholder="Search User, Name, Group..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-slate-100 border border-slate-200 rounded-2xl pl-12 pr-4 py-3 text-sm font-semibold tracking-wide text-slate-700 placeholder:text-slate-400 outline-none focus:ring-2 focus:ring-slate-300 transition-all"
          />
        </div>

        {/* ADD BUTTON */}
        <button
          onClick={() => {
            setEditId(null);
            setFormData(initialFormState);
            setShowForm(true);
            setUsernameAutoGenerated(false);
          }}
          className="px-6 py-3 bg-slate-900 text-white font-black text-xs uppercase rounded-2xl hover:bg-black transition-all shadow-lg"
        >
<span className="font-extrabold text-sm mr-1 leading-none">+</span>
  Add New User
        </button>
      </div>
    )}
  </div>


      {showForm ? (
        <div className="bg-white rounded-[32px] shadow-xl border border-slate-200 overflow-hidden animate-in slide-in-from-bottom-4 duration-500">
          <div className="bg-slate-50 border-b border-slate-200 px-8 py-4 flex justify-between items-center">
            <h3 className="font-black text-slate-800 uppercase tracking-tight text-sm">{editId ? 'Edit Staff Profile' : 'Staff Entry Form'}</h3>
            <button onClick={() => setShowForm(false)} className="text-slate-400 hover:text-slate-600"><X size={20} /></button>
          </div>

          <div className="p-8 flex flex-col lg:flex-row gap-10">
            <div className="flex flex-col items-center gap-4">
               <div className="w-48 h-48 rounded-[40px] bg-white border-2 border-dashed border-slate-200 overflow-hidden flex items-center justify-center relative group">
                  {formData.profileImage ? <img src={formData.profileImage} alt="Profile" className="w-full h-full object-cover" /> : <div className="flex flex-col items-center text-slate-300"><ImageIcon size={48} /><span className="text-[10px] font-black uppercase mt-2">No Photo</span></div>}
                  <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col items-center justify-center gap-2">
                    <button onClick={() => photoInputRef.current?.click()} className="p-2 bg-white rounded-full text-slate-800 hover:bg-slate-100"><Upload size={18} /></button>
                    <button onClick={startCamera} className="p-2 bg-white rounded-full text-slate-800 hover:bg-slate-100"><Camera size={18} /></button>
                  </div>
               </div>
               <div className="text-center">
                  <p className="text-[10px] font-black uppercase text-slate-400 tracking-widest">Staff Photo</p>
                  <div className="flex gap-2 mt-2">
                    <button onClick={() => photoInputRef.current?.click()} className="text-[9px] font-black uppercase text-blue-600 hover:underline">Upload</button>
                    <span className="text-slate-200">|</span>
                    <button onClick={startCamera} className="text-[9px] font-black uppercase text-blue-600 hover:underline">Capture</button>
                  </div>
               </div>
               <input type="file" ref={photoInputRef} onChange={(e) => handleFileChange(e, 'photo')} accept="image/*" className="hidden" />
            </div>

            <div className="flex-1 grid grid-cols-1 md:grid-cols-4 gap-6">
              <div className="md:col-span-4 grid grid-cols-1 md:grid-cols-4 gap-4">
                <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">Last Name <Mandatory /></label>
                  <input type="text" name="lastName" value={formData.lastName} onChange={handleInputChange} className={`w-full bg-white border ${errors.lastName ? 'border-rose-400 ring-1 ring-rose-400' : 'border-slate-300'} rounded-xl px-4 py-2.5 text-sm font-bold uppercase transition-all outline-none focus:ring-2 focus:ring-sky-500/20`} />
                  {errors.lastName && <p className="text-[10px] text-rose-500 font-bold pl-1 uppercase">{errors.lastName}</p>}
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">First Name <Mandatory /></label>
                  <input type="text" name="firstName" value={formData.firstName} onChange={handleInputChange} className={`w-full bg-white border ${errors.firstName ? 'border-rose-400 ring-1 ring-rose-400' : 'border-slate-300'} rounded-xl px-4 py-2.5 text-sm font-bold uppercase transition-all outline-none focus:ring-2 focus:ring-sky-500/20`} />
                  {errors.firstName && <p className="text-[10px] text-rose-500 font-bold pl-1 uppercase">{errors.firstName}</p>}
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">Middle Name</label>
                  <input type="text" name="middleName" value={formData.middleName} onChange={handleInputChange} className="w-full bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-sm font-bold uppercase outline-none focus:ring-2 focus:ring-sky-500/20 transition-all" />
                </div>
                <div className="space-y-1">
                  <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">Ext.</label>
                  <input type="text" name="extension" value={formData.extension} onChange={handleInputChange} placeholder="JR / III" className="w-full bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-sm font-bold uppercase outline-none focus:ring-2 focus:ring-sky-500/20 transition-all" />
                </div>
              </div>

              <div className="space-y-1 md:col-span-2">
                <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">Username <Mandatory /></label>
                <div className="relative group">
                  <input type="text" name="username" value={formData.username} onChange={handleUsernameChange} className={`w-full bg-white border ${errors.username ? 'border-rose-400 ring-1 ring-rose-400' : 'border-slate-300'} rounded-xl px-4 py-2.5 text-sm font-black text-slate-900 uppercase transition-all outline-none focus:ring-2 focus:ring-sky-500/20`} />
                  {!editId && !usernameAutoGenerated && <div className="absolute right-3 top-1/2 -translate-y-1/2 text-[8px] font-black text-blue-500 uppercase tracking-widest bg-blue-50 px-1.5 py-0.5 rounded">Suggested</div>}
                </div>
                {errors.username && <p className="text-[10px] text-rose-500 font-bold pl-1 uppercase">{errors.username}</p>}
              </div>

              <div className="space-y-1 md:col-span-2">
                <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">Custom Name (Display)</label>
                <input type="text" name="customName" value={formData.customName} onChange={handleInputChange} placeholder="E.G. MARIA RN" className="w-full bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-sm font-bold uppercase outline-none focus:ring-2 focus:ring-sky-500/20 transition-all" />
              </div>

              <div className="space-y-1 md:col-span-2">
                <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">Email Address <Mandatory /></label>
                <input type="email" name="email" value={formData.email} onChange={handleInputChange} className={`w-full bg-white border ${errors.email ? 'border-rose-400 ring-1 ring-rose-400' : 'border-slate-300'} rounded-xl px-4 py-2.5 text-sm font-bold transition-all outline-none focus:ring-2 focus:ring-sky-500/20`} />
                {errors.email && <p className="text-[10px] text-rose-500 font-bold pl-1 uppercase">{errors.email}</p>}
              </div>

              <div className="space-y-1 md:col-span-2">
                <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">Authorized Departments <Mandatory /></label>
                <div className={`grid grid-cols-1 gap-2 p-3 bg-white border ${errors.departments ? 'border-rose-400 ring-1 ring-rose-400' : 'border-slate-300'} rounded-xl max-h-[140px] overflow-y-auto transition-all`}>
                  {departments.map(d => (
                    <label key={d.id} className="flex items-center gap-3 cursor-pointer group">
                      <div onClick={() => toggleDepartment(d.code)} className={`w-5 h-5 rounded border flex items-center justify-center transition-all ${formData.departments.includes(d.code) ? 'bg-slate-900 border-slate-900 text-white' : 'bg-white border-slate-300'}`}>
                        {formData.departments.includes(d.code) && <Check size={12} strokeWidth={4} />}
                      </div>
                      <span className="text-[11px] font-bold text-slate-700 uppercase">{d.name}</span>
                    </label>
                  ))}
                </div>
                {errors.departments && <p className="text-[10px] text-rose-500 font-bold mt-1 uppercase pl-1">{errors.departments}</p>}
              </div>

              <div className="space-y-1 md:col-span-2 relative">
                <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">{editId ? 'New Password (Optional)' : 'Password'} {!editId && <Mandatory />}</label>
                <div className="relative">
                  <input type={showPassword ? 'text' : 'password'} name="password" value={formData.password} onChange={handleInputChange} className={`w-full bg-white border ${errors.password ? 'border-rose-400 ring-1 ring-rose-400' : 'border-slate-300'} rounded-xl px-4 py-2.5 text-sm font-bold pr-12 transition-all outline-none focus:ring-2 focus:ring-sky-500/20`} />
                  <button type="button" onClick={() => setShowPassword(!showPassword)} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400">{showPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button>
                </div>
                {errors.password && <p className="text-[10px] text-rose-500 font-bold mt-1 pl-1 uppercase leading-tight">{errors.password}</p>}
              </div>

              <div className="space-y-1 md:col-span-2 relative">
                <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">Confirm Password {!editId && <Mandatory />}</label>
                <div className="relative">
                  <input type={showConfirmPassword ? 'text' : 'password'} name="confirmPassword" value={formData.confirmPassword} onChange={handleInputChange} className={`w-full bg-white border ${errors.confirmPassword ? 'border-rose-400 ring-1 ring-rose-400' : 'border-slate-300'} rounded-xl px-4 py-2.5 text-sm font-bold pr-12 transition-all outline-none focus:ring-2 focus:ring-sky-500/20`} />
                  <button type="button" onClick={() => setShowConfirmPassword(!showConfirmPassword)} className="absolute right-4 top-1/2 -translate-y-1/2 text-slate-400">{showConfirmPassword ? <EyeOff size={16} /> : <Eye size={16} />}</button>
                </div>
                {errors.confirmPassword && <p className="text-[10px] text-rose-500 font-bold mt-1 pl-1 uppercase">{errors.confirmPassword}</p>}
              </div>

              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">User Group</label>
                <select name="userGroup" value={formData.userGroup} onChange={handleInputChange} className="w-full bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-sm font-bold uppercase outline-none focus:ring-2 focus:ring-sky-500/20 transition-all">
                  <option value={UserGroup.User}>USER</option>
                  <option value={UserGroup.Admin}>ADMIN</option>
                </select>
              </div>
              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">User Type</label>
                <select name="userType" value={formData.userType} onChange={handleInputChange} className="w-full bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-sm font-bold uppercase outline-none focus:ring-2 focus:ring-sky-500/20 transition-all">
                  <option value={UserType.NURSE}>NURSE</option>
                  <option value={UserType.DOCTOR}>DOCTOR</option>
                  <option value={UserType.MIDWIFE}>MIDWIFE</option>
                  <option value={UserType.ADMIN}>ADMIN</option>
                  <option value={UserType.OTHERS}>OTHERS</option>
                </select>
              </div>
              <div className="space-y-1">
                <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">Status</label>
                <select
  name="isActive"
  value={formData.isActive ? "true" : "false"}
  onChange={(e) =>
    setFormData(prev => ({
      ...prev,
      isActive: e.target.value === "true"
    }))
  }
  className="w-full bg-white border border-slate-300 rounded-xl px-4 py-2.5 text-sm font-bold uppercase outline-none focus:ring-2 focus:ring-sky-500/20 transition-all"
>
  <option value="true">ACTIVE</option>
  <option value="false">DEACTIVATED</option>
</select>
              </div>

<div className="space-y-1">
  <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">
    Default Dept <Mandatory />
  </label>

  <select
    name="defaultDepartment"
    value={formData.defaultDepartment}
    onChange={handleInputChange}
    className={`w-full bg-white border ${
      errors.defaultDepartment
        ? 'border-rose-400 ring-1 ring-rose-400'
        : 'border-slate-300'
    } rounded-xl px-4 py-2.5 text-sm font-bold uppercase transition-all outline-none focus:ring-2 focus:ring-sky-500/20`}
  >
    <option value="">SELECT DEFAULT</option>

    {formData.departments.map(code => {
      const dept = departments.find(d => d.code === code);
      return (
        <option key={code} value={code}>
          {dept ? dept.name : code}
        </option>
      );
    })}
  </select>
</div>


              {/* Doctor Name Dropdown - Enabled only when user type is DOCTOR */}
              <div className="space-y-1 md:col-span-2">
                <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider">
                  Associate Doctor Name {formData.userType === UserType.DOCTOR && <Mandatory />}
                </label>
                <select 
                  name="doctorName" 
                  value={formData.doctorName || ''} 
                  onChange={handleInputChange} 
                  disabled={formData.userType !== UserType.DOCTOR}
                  className={`w-full bg-white border ${errors.doctorName ? 'border-rose-400 ring-1 ring-rose-400' : 'border-slate-300'} rounded-xl px-4 py-2.5 text-sm font-bold uppercase transition-all outline-none focus:ring-2 focus:ring-sky-500/20 disabled:bg-slate-50 disabled:text-slate-300 disabled:cursor-not-allowed`}
                >
                  <option value="">SELECT DOCTOR</option>
                  {DOCTORS.map(doc => (
                    <option key={doc} value={doc}>{doc}</option>
                  ))}
                </select>
                {errors.doctorName && <p className="text-[10px] text-rose-500 font-bold mt-1 pl-1 uppercase">{errors.doctorName}</p>}
              </div>

              <div className="space-y-1 md:col-span-4">
                <label className="text-[10px] font-black uppercase text-slate-500 tracking-wider block">E-Signature</label>
                <div className="relative group">
                  {formData.eSignature ? (
                    <div className="w-full bg-white border-2 border-slate-200 rounded-xl p-4 flex items-center justify-between group transition-all hover:border-blue-300">
                      <div className="flex items-center gap-4 flex-1">
                        <div className="w-24 h-12 bg-slate-50 rounded border border-slate-100 overflow-hidden flex items-center justify-center p-1">
                          <img src={formData.eSignature} alt="E-Signature Preview" className="max-w-full max-h-full object-contain" />
                        </div>
                        <div>
                          <p className="text-[10px] font-black uppercase text-slate-800 tracking-tight">Signature Verified</p>
                          <p className="text-[8px] font-bold text-slate-400 uppercase tracking-widest">Digital Auth ID Attached</p>
                        </div>
                      </div>
                      <div className="flex gap-2">
                        <button 
                          onClick={() => fileInputRef.current?.click()} 
                          className="p-2.5 bg-slate-50 text-slate-600 rounded-lg hover:bg-blue-50 hover:text-blue-600 transition-all shadow-sm"
                          title="Replace Signature"
                        >
                          <RefreshCw size={14} />
                        </button>
                        <button 
                          onClick={() => setFormData(prev => ({ ...prev, eSignature: null }))}
                          className="p-2.5 bg-slate-50 text-slate-600 rounded-lg hover:bg-rose-50 hover:text-rose-600 transition-all shadow-sm"
                          title="Remove Signature"
                        >
                          <Trash2 size={14} />
                        </button>
                      </div>
                    </div>
                  ) : (
                    <button 
                      onClick={() => fileInputRef.current?.click()} 
                      className="w-full bg-white border-2 border-dashed border-slate-200 rounded-xl py-8 px-4 text-xs font-black text-slate-400 flex flex-col items-center justify-center gap-3 hover:bg-slate-50 transition-all group-hover:border-blue-400 group-hover:text-blue-500"
                    >
                      <div className="w-12 h-12 rounded-full bg-slate-50 flex items-center justify-center group-hover:bg-blue-50 transition-colors">
                        <Upload size={20} />
                      </div>
                      <span className="uppercase tracking-[0.2em]">Upload Digital Signature</span>
                      <span className="text-[8px] font-bold text-slate-300 uppercase tracking-[0.1em]">PNG, JPG, or GIF (Transparency Recommended)</span>
                    </button>
                  )}
                </div>
                <input type="file" ref={fileInputRef} onChange={(e) => handleFileChange(e, 'signature')} accept="image/*" className="hidden" />
              </div>

              <div className="md:col-span-4 mt-6 flex justify-end gap-3 pt-6 border-t border-slate-100">
                 <button onClick={() => setShowForm(false)} className="px-8 py-3 bg-slate-100 text-slate-600 font-black text-xs uppercase rounded-xl hover:bg-slate-200 transition-all">Cancel Entry</button>
                 <button onClick={handleSave} className="px-10 py-3 bg-slate-900 text-white font-black text-xs uppercase rounded-xl hover:bg-black transition-all shadow-lg flex items-center gap-2"><Save size={16} /> {editId ? 'Update Clinical User' : 'Save Clinical User'}</button>
              </div>
            </div>
          </div>
        </div>
      ) : (
  <>

    <div className="bg-white rounded-[32px] shadow-sm border border-slate-200 overflow-hidden">
      <table className="w-full text-left">
        <thead>
          <tr className="bg-slate-50 border-b border-slate-200">
            <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest w-32 text-center">
              Username
            </th>
            <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">
              Full Name
            </th>
            <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">
              Group
            </th>
            <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest text-center">
              Status
            </th>
            <th className="px-8 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest text-right">
              Actions
            </th>
          </tr>
        </thead>

        <tbody className="divide-y divide-slate-100">
  {filteredUsers.map((staff: any) => {
   const isActive = staff.isActive;

    return (
      <tr
        key={staff.id}
        className="hover:bg-slate-50 transition-colors group"
      >
        {/* USERNAME */}
        <td className="px-8 py-5 text-center">
          <span className="text-sm font-black text-slate-900 uppercase tracking-tight">
            {staff.username}
          </span>
        </td>

        {/* FULL NAME */}
        <td className="px-8 py-5">
          <div className="flex flex-col">
            <span className="font-black text-slate-700 text-sm uppercase">
              {staff.fullName}
            </span>

            {staff.defaultDepartment && (
              <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">
                Home: {staff.defaultDepartment}
              </span>
            )}

            {staff.userType === UserType.DOCTOR &&
              staff.doctorName && (
                <span className="text-[9px] font-bold text-blue-600 uppercase tracking-tight">
                  Assoc: {staff.doctorName}
                </span>
              )}
          </div>
        </td>

        {/* GROUP */}
        <td className="px-8 py-5 text-center">
          <span
            className={`px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-wide ${
              staff?.groupColor && colorMap[staff.groupColor]
                ? colorMap[staff.groupColor]
                : ""
            }`}
          >
            {staff.userGroup}
          </span>
        </td>

        {/* STATUS */}
        <td className="px-8 py-5 text-center">
          <span
            className={`px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-wide ${
              isActive
                ? "bg-emerald-100 text-emerald-700"
                : "bg-slate-200 text-slate-600"
            }`}
          >
            {staff.statusLabel}
          </span>
        </td>

        {/* ACTIONS */}
        <td className="px-8 py-5 text-right">
          <div className="flex items-center justify-end gap-4">

            {/* EDIT */}
            <button
              onClick={() => handleEdit(staff)}
              className="text-blue-600 hover:text-blue-800 font-black text-[10px] uppercase tracking-wide flex items-center gap-1.5 transition-colors"
            >
              <Edit2 size={14} />
              Edit
            </button>

            {/* TOGGLE */}
            <button
              onClick={() =>
  setStatusModal({
    isOpen: true,
    user: staff,
    action: staff.isActive ? "deactivate" : "activate" })
              }
              className={`font-black text-[10px] uppercase flex items-center gap-1.5 transition-colors ${
                isActive
                  ? "text-rose-600 hover:text-rose-800"
                  : "text-emerald-600 hover:text-emerald-800"
              }`}
            >
              <Eye size={14} />
              {isActive ? "Deactivate" : "Activate"}
            </button>

          </div>
        </td>
      </tr>
    );
  })}
        </tbody>
      </table>
    </div>
  </>
)}
<StatusConfirmationModal
  isOpen={statusModal.isOpen}
  targetName={statusModal.user?.fullName || ""}
  action={statusModal.action}
  onConfirm={handleToggleStatus}
  onCancel={() =>
    setStatusModal({
      isOpen: false,
      user: null,
      action: null
    })
  }
/>

<TransactionOverlay 
  status={txStatus} 
  message={txMsg}
  onClose={() => setTxStatus("idle")}
/>
</div>
);
};

